name: Terraform plan, apply, and destroy

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -var="profile=dev"

    - name: Comment Plan Output
      if: ${{ github.actor != github.repository_owner }}
      uses: unsplash/comment-on-pr@v1
      with:
        message: |
          **Terraform Plan:**
          ```
          ${{ steps.plan.outputs.stdout }}
          ```

    - name: Terraform Apply
      if: github.event.action == 'closed' && github.event.pull_request.merged == true
      run: terraform apply -auto-approve -var="profile=dev"

    - name: Terraform Destroy
      if: github.event.pull_request.merged == true
      run: terraform destroy -auto-approve -var="profile=dev"
